### ISSUE TITLE
图片遮罩

### ISSUE THREAD

**Issue by yangjaixi** [yangjaixi/yangjaixi.github.io#10]
```css
.map_mask {
    background-color: #000;
    img {
      opacity: .6
    }
  }
```
图片的容器设置背景颜色，图片设置透明度，模拟图片遮罩层。
