### ISSUE TITLE
旋转样式

### ISSUE THREAD

**Issue by yangjaixi** [yangjaixi/yangjaixi.github.io#9]
```css
@keyframes rotate {
  0%,
  100% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.login_logo {
  animation: rotate 2s linear infinite;
}
````
